language: python
python:
- 3.7
stages:
- lint
- test
- deploy
jobs:
  include:
  - stage: lint
    install:
    - pip install pre-commit
    - pre-commit install-hooks
    script:
    - pre-commit run --all-files
  - stage: test
    install:
    - pip install poetry
    - poetry install -v
    - pip install codecov
    script:
    - poetry run pytest
    - codecov
  - stage: deploy
    if: branch = master AND type != pull_request
    install:
    - pip install poetry
    script:
    - poetry publish --username $PYPI_USER --password $PYPI_PASSWORD --build
    on:
      branch: master
      tags: true
env:
  global:
  - secure: KFQG7n0BP8hhiWJxztBloPzYEpABZpRWXH1xPNFLGDpQKixgSNwvvsvh0730NCDN32z2+A3zOzExHx2Le7wwi7tvkvHkpDq5BVbngmMCwB1m9g1VBKs+Uq55IMj9a2YYkw63ivx1VVLPr59vJqpQI54mgbHc15IJmtPYTrLGzt6LGHhbT3N0W4z9DwHkrb0vks/rBKwqtgGh+cUjNsrji0lDiumNDUT7v2gwctejNliq0eG6TJcxPc4dPcKF1PXazwCi3h2/ZHVjrPGT+MS3O80PMzWmD0tXTeMtaeuy5d3q6IEn8VJLPzPBjZOraPr6ADfL2agFTdeEW2wRM0Ex6wBOB8JFyFRDeFLfk+ed4XWNNbSMPRROJ1OxqTrH1hDYS9/YkPS9Z/lAjOP1nxHFzlgLzn4de7mhxo1sfMWpoES559+3xE+yZGGNWq/IYFAipD+PMlGYKGgUTCq1hCkETpceNI4m3getqUSUaV2KNrzG26oodKEw1ZxE5VBpjTmteb/Ghm4Mwh4DFEodlMVPHdrm38nyqRQbG4QClnbrEk9SyD2Kbet+96XKKFtB0ksvZ2CnCb3AFnJaWDJ/qFtFm706DaZFXcytJKMe5YTcBHczSL1LXxKJmfItW7rfMNwHE5icLsC1SG02ASjilErkEMf/FOD9Gg8LpIxCgKHQZM8=
  - secure: l/88exD+5/y8L/tkCamQfwXQjIiGQAZcdhhWBNLNO8q8/+YNKFEVsMVaKiMTVDfyTiluSsyAzdTCryn7KGGvnD1GZTqQmXTBy5o0eUGAZtBw0BQu0RJW37BP5VlQbh2AMh3pAlds3iUPrquSXcj12GmWveCrUvAzI2f9+B5SL9wPgoxXYUydHmovjt7UqXEXMqSN0kD9SksEB0cqG+emPz4psrggkzIYO1/xFpaN5ijNzGVLPzOq4Sv3+Xp2AcrnUbfXOqleKJdJIGQOTb71C2lO/qjYi4TJCvXYfb9FII6f40i9aj8CHb9FL31WuLBDAkuEelzJZfHObw1HTgkEGNzGf0j2SuS6vnCIXW0dGjTWWeyxs/UlbJm2FCehLVR7vRT0QKA4Dapk5nkjAnKyhgK6Zr+bowU1nTBoGKjt74Y8J6yl7ONFXdfN+HHdw5r1yOCfK9BBjazWxu1WdwpjBIlXDKkdlCMyMzEg16bpbxE6qZAjvnFTJA+a6Ai67rspAuLTNg3iVPcNHz1cEzESTMwq0veN6FTHbd0B6LsSC3z+GJcDlLRpZesr2t9XindMh3axMlQ20KNAaV5wkJPGrNTTw5+dASECj9dW3hqF0YwmCVGJV7w6dWe9499rBkqMdbjYPDdnxzIfMJE0jy0T/nW8mmBBnxA8x9d56mA1P04=
